# Generated by Django 4.1.4 on 2022-12-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exercicio_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ('categoria',), 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Peitoral', 'Peitoral'), ('Pernas', 'Pernas'), ('Costas', 'Costas'), ('Bíceps', 'Bíceps'), ('Tríceps', 'Tríceps')], max_length=50, null=True),
        ),
    ]
